blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/Mr-Anonymous-Guy/Repo_Cone_System/discussions
    about: Please ask questions and discuss ideas in GitHub Discussions.
